// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9nbvzgdxEoz-xe95gBjnmpMV30_3djWs',
    appId: '1:214503911940:web:43ce799c1c22eec28c7b51',
    messagingSenderId: '214503911940',
    projectId: 'pasanaku-9748f',
    authDomain: 'pasanaku-9748f.firebaseapp.com',
    storageBucket: 'pasanaku-9748f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSVKumxuKR19v8zO7CuYYiI18hWnd4pI',
    appId: '1:214503911940:android:1cd7a49fb1035ff88c7b51',
    messagingSenderId: '214503911940',
    projectId: 'pasanaku-9748f',
    storageBucket: 'pasanaku-9748f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBupRdyZW8LmWaTtR5qkPSbO6ym-C9eBYk',
    appId: '1:214503911940:ios:8bc257ec41316aa88c7b51',
    messagingSenderId: '214503911940',
    projectId: 'pasanaku-9748f',
    storageBucket: 'pasanaku-9748f.appspot.com',
    iosBundleId: 'com.example.pasana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBupRdyZW8LmWaTtR5qkPSbO6ym-C9eBYk',
    appId: '1:214503911940:ios:8bc257ec41316aa88c7b51',
    messagingSenderId: '214503911940',
    projectId: 'pasanaku-9748f',
    storageBucket: 'pasanaku-9748f.appspot.com',
    iosBundleId: 'com.example.pasana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9nbvzgdxEoz-xe95gBjnmpMV30_3djWs',
    appId: '1:214503911940:web:3d396aaf433c371f8c7b51',
    messagingSenderId: '214503911940',
    projectId: 'pasanaku-9748f',
    authDomain: 'pasanaku-9748f.firebaseapp.com',
    storageBucket: 'pasanaku-9748f.appspot.com',
  );
}
